routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::group(['middleware' =>['auth']], function(){
Route::get('/', 'HomeController@index')->name('index');
Route::get('/home', 'HomeController@index')->name('home');

Route::resource('/bannerImage', 'AdBannerController');
    
Route::resource('/notice', 'NoticeController');
Route::get('/ajaxGetNoticeFile', 'NoticeController@getNoticeFile')->name('ajaxGetNoticeFile');
Route::delete('/noticefile/{id}/delete', 'NoticeController@deleteNoticeFile')->name('deleteNoticeFile');

Route::resource('/contact', 'ContactController');

Route::resource('/note', 'NoteController');
Route::get('/ajaxGetNoteFile', 'NoteController@getNoteFile')->name('ajaxGetNoteFile');
Route::delete('/notefile/{id}/delete', 'NoteController@deleteNoteFile')->name('deleteNoteFile');

Route::resource('/result', 'ResultController');
Route::get('/ajaxGetResultFile', 'ResultController@getResultFile')->name('ajaxGetResultFile');
Route::delete('/resultfile/{id}/delete', 'ResultController@deleteResultFile')->name('deleteResultFile');

Route::resource('/article', 'ArticleController');
Route::get('/ajaxGetArticleFile', 'ArticleController@getArticleFile')->name('ajaxGetArticleFile');
Route::delete('/articlefile/{id}/delete', 'ArticleController@deleteArticleFile')->name('deleteArticleFile');

Route::resource('/syllabi', 'SyllabusController');
Route::get('/ajaxGetSyllabusFile', 'SyllabusController@getSyllabusFile')->name('ajaxGetSyllabusFile');
Route::delete('/syllabusfile/{id}/delete', 'SyllabusController@deleteSyllabusFile')->name('deleteSyllabusFile');

Route::resource('/question', 'OldQuestionController');
Route::get('/ajaxGetOldQuestionFile', 'OldQuestionController@getOldQuestionFile')->name('ajaxGetOldQuestionFile');
Route::delete('/oldquestionfile/{id}/delete', 'OldQuestionController@deleteOldQuestionFile')->name('deleteOldQuestionFile');

Route::resource('/taxonomies', 'TaxonomyController');
Route::get('/ajaxGetTaxonomyFile', 'TaxonomyController@getTaxonomyFile')->name('ajaxGetTaxonomyFile');
Route::delete('/taxonomyfile/{id}/delete', 'TaxonomyController@deleteTaxonomyFile')->name('deleteTaxonomyFile');

Route::resource('/capsule', 'CapsuleController');
Route::get('/ajaxGetCapsuleFile', 'CapsuleController@getCapsuleFile')->name('ajaxGetCapsuleFile');
Route::delete('/capsulefile/{id}/delete', 'CapsuleController@deleteCapsuleFile')->name('deleteCapsuleFile');


Route::resource('/department', 'DepartmentController');
Route::resource('/category', 'CategoryController');

Route::get('/booking', 'BookingController@index')->name('booking.index');
Route::get('/booking/{id}', 'BookingController@view')->name('booking.view');
Route::get('/booking/delete/{id}', 'BookingController@delete')->name('booking.destroy');
});

app/Taxonomy.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Taxonomy extends Model
{
    public function taxonomy_file(){
    	return $this->hasMany('App\TaxonomyFile');
    }
}

app/Http/Controllers/Api/v1/TaxonomyController.php
<?php

namespace App\Http\Controllers\Api\v1;

use Auth;
use Validator;
use App\Taxonomy;
use Illuminate\Http\Request;
use App\Traits\AppAuthorization;
use App\Http\Controllers\Controller;
use \Illuminate\Http\Response as Res;

class TaxonomyController extends BaseController
{
    /** 
        *   @OA\get(
        *     path="/taxonomy/filter",
        *     tags={"Search"},
        *     description="taxonomy filter",
        *     summary="taxonomy filter",
        *     security= {{"App_Key":"",}},
        *     @OA\Response(response=200,description="note filtered successful",
        *         @OA\JsonContent(type="object",
        *         ),
        *         @OA\Link(
        *             link="SearchFilter",
        *             operationId="SearchFilter",
        *             parameters={
        *                   "year":"2019",
        *                   "offset":"1",
        *                   "limit":"10",
        *             },
        *          ),
        *     ),
        *     @OA\Response( response="default",description="unexpected error",
        *         @OA\JsonContent(type="object",
        *         ),
        *     ),
        * )
    */
    public function filter(Request $request)
    {
    	$data = Taxonomy::orderBy('created_at','desc')
    				->with('taxonomy_file')
    				->get();
    	if(count($data)<1) {
            $this->setStatusCode(Res::HTTP_NOT_FOUND);
            return $this->respondNotFound('No taxonomy found');
        }
        $this->setStatusCode(Res::HTTP_OK);
        return $this->sendSuccessResponse($data, 'taxonomy list success');
    }
}

app/Http/Controllers/TaxonomyController.php
<?php

namespace App\Http\Controllers;

use File;
use App\Taxonomy;
use App\TaxonomyFile;
use Illuminate\Http\Request;

class TaxonomyController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $taxonomies = Taxonomy::orderBy('id','desc')->paginate(10);
        return view('admin.taxonomy.index',compact('taxonomies'));
    }
    public function getTaxonomyFile(Request $request){
        $data = TaxonomyFile::where('taxonomy_id',$request->id)->get();
        $response = array(
            'status' => 'success',
            'msg' => $data
        );
        return response()->json($response);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.taxonomy.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'title' => 'required',
            'file_title' => 'required',
            'files' => 'required',
            'files.*' => 'mimes:doc,pdf,docx'
        ]);
        $data = new Taxonomy;
        $data->title = $request->title;
        $data->description = $request->description;
        $data->save();

        if($request->hasfile('files'))
         {
            foreach($request->file('files') as $file)
            {
                $title=$file->getClientOriginalName();
                $name = '/taxonomy/'.str_random(10).'.'.$file->getClientOriginalExtension();
                $file->move(public_path().'/taxonomy/', $name);  
                $dataFile = new TaxonomyFile;
                $dataFile->taxonomy_id = $data->id;
                $dataFile->file_title = $request->file_title;
                $dataFile->file_name = $name;
                $dataFile->save();
            }
         }
        return redirect()->route('taxonomies.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $taxonomy = Taxonomy::find($id);
        return view('admin.taxonomy.edit',compact('taxonomy'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'title' => 'required',
            'file_title' => 'sometimes',
            'files' => 'required',
            'files.*' => 'mimes:doc,pdf,docx'
        ]);
        $data = Taxonomy::find($id);
        $data->title = $request->title;
        $data->description = $request->description;
        $data->save();

        if($request->hasfile('files'))
         {
            foreach($request->file('files') as $file)
            {
                $title=$file->getClientOriginalName();
                $name = '/taxonomy/'.str_random(10).'.'.$file->getClientOriginalExtension();
                $file->move(public_path().'/taxonomy/', $name);  
                $dataFile = new TaxonomyFile;
                $dataFile->taxonomy_id = $data->id;
                $dataFile->file_title = $request->file_title;
                $dataFile->file_name = $name;
                $dataFile->save();
            }
         }
        return redirect()->route('taxonomies.edit',$id);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $files = TaxonomyFile::where('taxonomy_id',$id)->get();
        foreach($files as $file){
            if (File::exists(public_path($file->file_name))) {
                File::delete(public_path($file->file_name));
            }
            $file->delete();
        }
        Taxonomy::find($id)->delete();
        return redirect()->route('taxonomies.index');
    }
    public function deleteTaxonomyFile($id)
    {
        $file = TaxonomyFile::find($id);
        if (File::exists(public_path($file->file_name))) {
            File::delete(public_path($file->file_name));
        }
        $file->delete();
        return redirect()->back();
    }
}

resources/views/admin/taxonomy/create.blade.php
@extends('layouts.app')
@section('styles')
<!-- bootstrap datepicker -->
<link rel="stylesheet" href="{{asset('adminlte/bower_components/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css')}}">
@endsection
@section('content')
<div class="container">
  <div class="row justify-content-center">
      <div class="col-md-8">
          <div class="box">
              <div class="box-header">
                <h3 class="box-title">Add Taxonomy</h3>
              </div>
              <div class="box-body">
              <form  method="POST" action="{{route('taxonomies.store')}}" enctype="multipart/form-data">
                   {{csrf_field()}}
                   <div class="form-group">
                      <label>Title:</label>
                      <div class="input-group">
                          <div class="input-group-addon">
                            <i class="fa fa-building"></i>
                          </div>
                          <input type="text" class="form-control" name="title" placeholder="title" required>
                      </div>
                   </div>
                   <div class="form-group">
                      <label>Description:</label>
                      <div class="input-group">
                          <div class="input-group-addon">
                            <i class="fa fa-building"></i>
                          </div>
                          <textarea name="description" class="form-control"></textarea>
                      </div>
                   </div>
                   <div class="form-group">
                      <label>File Title:</label>
                      <div class="input-group">
                          <div class="input-group-addon">
                            <i class="fa fa-building"></i>
                          </div>
                          <input type="text" class="form-control" name="file_title" placeholder="file title" required>
                      </div>
                   </div>
                   <div class="form-group">
                      <label>File:</label>
                      <div class="input-group">
                          <div class="input-group-addon">
                            <i class="fa fa-building"></i>
                          </div>
                          <input type="file" class="form-control" name="files[]" required>
                      </div>
                   </div>
                  </div>
                   <div class="form-group">
                     <div class="form-input">
                       <input type="submit" class="btn btn-xs btn-primary" value="SUBMIT">
                     </div>
                   </div>
                 </form>
              </div>
          </div>
      </div>
  </div>
</div>
@endSection
@section('scripts')
<script>
  
</script>
@endsection

resources/views/admin/taxonomy/edit.blade.php
@extends('layouts.app')
@section('styles')
<!-- bootstrap datepicker -->
<link rel="stylesheet" href="{{asset('adminlte/bower_components/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css')}}">
@endsection
@section('content')
<div class="container">
  <div class="row justify-content-center">
      <div class="col-md-8">
          <div class="box">
              <div class="box-header">
                <h3 class="box-title">Edit Taxonomy</h3>
              </div>
              <div class="box-body">
              <form  method="POST" action="{{route('taxonomies.update',$taxonomy->id)}}" enctype="multipart/form-data">
                   {{csrf_field()}}
                   {{method_field('PUT')}}
                   <div class="form-group">
                      <label>Title:</label>
                      <div class="input-group">
                          <div class="input-group-addon">
                            <i class="fa fa-building"></i>
                          </div>
                          <input type="text" class="form-control" name="title" id="title" placeholder="title" value="{{$taxonomy->title}}" required>
                      </div>
                   </div>
                   <div class="form-group">
                      <label>Description:</label>
                      <div class="input-group">
                          <div class="input-group-addon">
                            <i class="fa fa-building"></i>
                          </div>
                          <textarea name="description" class="form-control">{{$taxonomy->description}}</textarea> 
                      </div>
                   </div>
                   <div class="form-group">
                      <label>File Title:</label>
                      <div class="input-group">
                          <div class="input-group-addon">
                            <i class="fa fa-building"></i>
                          </div>
                          <input type="text" class="form-control" name="file_title" placeholder="file title">
                      </div>
                   </div>
                   <div class="form-group">
                      <label>File:</label>
                      <div class="input-group">
                          <div class="input-group-addon">
                            <i class="fa fa-building"></i>
                          </div>
                          <input type="file" class="form-control" name="files[]">
                      </div>
                   </div>
                   <div id="file-action" class="row"></div>
                  </div>
                   <div class="form-group">
                     <div class="form-input">
                       <input type="submit" class="btn btn-xs btn-primary" value="SUBMIT">
                     </div>
                   </div>
                 </form>
              </div>
          </div>
      </div>
  </div>
</div>

@endSection
@section('scripts')
<script>

  $(document).ready(function(){
    var CSRF_TOKEN = $('meta[name="csrf-token"]').attr('content');
    var data = $('#title').val();
    if(data){
      $.ajax({
          url: '{{route('ajaxGetTaxonomyFile')}}',
          data:{
              _token: CSRF_TOKEN,
              id: <?php echo $taxonomy->id; ?>,
          },
          dataType: 'JSON',
          success:function(data){
              console.log(data.msg)
              var files = data.msg
              $('#file-action').html('');
              $.each(files, function(index, value){
                var url = "{{url('/taxonomyfile')}}"+"/"+(value.id)+'/delete';
                $('#file-action').append('<div class="col-md-2">'+(value.file_title)+'<form method="post" action='+url+'>{{csrf_field()}}{{method_field('DELETE')}}<button type="submit" class="btn btn-xs btn-danger"><i class="fa fa-trash" aria-hidden="true"></i></button></form></div>');
                  // $('#file-action').append($('<option>',{value:value.id}).text(value.name));
                  console.log(value);
              });
          }
      })
    }
  })
</script>
@endsection

resources/views/admin/taxonomy/index.blade.php
@extends('layouts.app')
@section('styles')
<!-- DataTables -->
<link rel="stylesheet" href="{{asset('adminlte/bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css')}}">
@endsection
@section('content')
<script src="{{asset('adminlte/bower_components/ckeditor/ckeditor.js')}}"></script>
<div class="container">
  <div class="row justify-content-center">
      <div class="col-md-10">
          <div class="box">
              <div class="box-header">
                <h3 class="box-title">Taxonomy</h3>
                <div class="pull-right">
                <a href="{{route('taxonomies.create')}}" class="btn btn-xs btn-primary">Add Taxonomy</a>
                </div>
              </div>
              <div class="box-body">
                <table id="dataTable" class="table table-bordered table-hover">
                  <thead>
                   <tr>
                    <th>SN</th>
                    <th>Title</th>
                    <th>File</th>
                    <th>Action</th>
                  </tr>
                 </thead>
                 <tbody>
                 @foreach($taxonomies as $k=>$taxonomy)
                 <tr>
                   <td>{{$k+1}}</td>
                   <td>{{$taxonomy->title}}</td>
                   <td>
                     @foreach($taxonomy->taxonomy_file as $file)
                      <li>
                        <a href="{{asset($file->file_name)}}">{{$file->file_title}}</a>
                      </li>
                     @endforeach
                   </td>
                   <td>
                     <form action="{{route('taxonomies.destroy',$taxonomy->id)}}" method="post">
                     <a href="{{route('taxonomies.edit',$taxonomy->id)}}" class="btn btn-xs btn-warning">EDIT</a>
                      {{csrf_field()}}
                      {{method_field('DELETE')}}
                      <input type="submit" class="btn btn-xs btn-danger" value="DELETE">
                     </form>
                   </td>
                 </tr>
                 @endforeach
                 </tbody>
               </table>
               <div class="text-center">
                 {{ $taxonomies->links() }}
               </div>  
            </div>
        </div>
    </div>
  </div>
</div>
@endSection
@section('scripts')
<script src="{{asset('adminlte/bower_components/datatables.net/js/jquery.dataTables.min.js')}}"></script>
<script src="{{asset('adminlte/bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js')}}"></script>
<script>
//data table
    $('#dataTable').DataTable({
      'paging'      : false,
      'lengthChange': false,
      'searching'   : false,
      'ordering'    : true,
      'info'        : false,
      'autoWidth'   : false
    });
</script>
@endsection