routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::group(['middleware' =>['auth']], function(){
Route::get('/', 'HomeController@index')->name('index');
Route::get('/home', 'HomeController@index')->name('home');

Route::resource('/bannerImage', 'AdBannerController');
    
Route::resource('/notice', 'NoticeController');
Route::get('/ajaxGetNoticeFile', 'NoticeController@getNoticeFile')->name('ajaxGetNoticeFile');
Route::delete('/noticefile/{id}/delete', 'NoticeController@deleteNoticeFile')->name('deleteNoticeFile');

Route::resource('/contact', 'ContactController');

Route::resource('/note', 'NoteController');
Route::get('/ajaxGetNoteFile', 'NoteController@getNoteFile')->name('ajaxGetNoteFile');
Route::delete('/notefile/{id}/delete', 'NoteController@deleteNoteFile')->name('deleteNoteFile');

Route::resource('/result', 'ResultController');
Route::get('/ajaxGetResultFile', 'ResultController@getResultFile')->name('ajaxGetResultFile');
Route::delete('/resultfile/{id}/delete', 'ResultController@deleteResultFile')->name('deleteResultFile');

Route::resource('/article', 'ArticleController');
Route::get('/ajaxGetArticleFile', 'ArticleController@getArticleFile')->name('ajaxGetArticleFile');
Route::delete('/articlefile/{id}/delete', 'ArticleController@deleteArticleFile')->name('deleteArticleFile');

Route::resource('/syllabi', 'SyllabusController');
Route::get('/ajaxGetSyllabusFile', 'SyllabusController@getSyllabusFile')->name('ajaxGetSyllabusFile');
Route::delete('/syllabusfile/{id}/delete', 'SyllabusController@deleteSyllabusFile')->name('deleteSyllabusFile');

Route::resource('/question', 'OldQuestionController');
Route::get('/ajaxGetOldQuestionFile', 'OldQuestionController@getOldQuestionFile')->name('ajaxGetOldQuestionFile');
Route::delete('/oldquestionfile/{id}/delete', 'OldQuestionController@deleteOldQuestionFile')->name('deleteOldQuestionFile');

Route::resource('/taxonomies', 'TaxonomyController');
Route::get('/ajaxGetTaxonomyFile', 'TaxonomyController@getTaxonomyFile')->name('ajaxGetTaxonomyFile');
Route::delete('/taxonomyfile/{id}/delete', 'TaxonomyController@deleteTaxonomyFile')->name('deleteTaxonomyFile');

Route::resource('/capsule', 'CapsuleController');
Route::get('/ajaxGetCapsuleFile', 'CapsuleController@getCapsuleFile')->name('ajaxGetCapsuleFile');
Route::delete('/capsulefile/{id}/delete', 'CapsuleController@deleteCapsuleFile')->name('deleteCapsuleFile');


Route::resource('/department', 'DepartmentController');
Route::resource('/category', 'CategoryController');

Route::get('/booking', 'BookingController@index')->name('booking.index');
Route::get('/booking/{id}', 'BookingController@view')->name('booking.view');
Route::get('/booking/delete/{id}', 'BookingController@delete')->name('booking.destroy');
});

app/AdBanner.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class AdBanner extends Model
{
    protected $table = 'ad_banners';    
}

app/Http/Controllers/AdBannerController.php
<?php

namespace App\Http\Controllers;

use File;   
use App\AdBanner;
use Illuminate\Http\Request;

class AdBannerController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $banners = AdBanner::orderBy('created_at','desc')->paginate(10);
        return view('admin.adbanner.index',compact('banners'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.adbanner.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'file_title' => 'sometimes',
            'status' => 'required',
            'image' => 'required|mimes:jpeg,png,jpg,gif,svg'
        ]);
        if($request->hasfile('image'))
        {
            $image =$request->file('image');
            $title=$image->getClientOriginalName();
            $name = '/banner/'.str_random(10).'.'.$image->getClientOriginalExtension();
            $image->move(public_path().'/banner/', $name);
            $dataFile = new AdBanner;
            $dataFile->file_title = $request->file_title;
            $dataFile->status = $request->status;
            $dataFile->file_name = $name;
            $dataFile->save();
        }
        return redirect()->route('bannerImage.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $banner = AdBanner::find($id);
        return view('admin.adbanner.edit',compact('banner'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'file_title' => 'sometimes',
            'status' => 'required',
            'image' => 'sometimes|mimes:jpeg,png,jpg,gif,svg'
        ]);
        $dataFile = AdBanner::find($id);
        $dataFile->file_title = $request->file_title;
        $dataFile->status = $request->status;
        if($request->hasfile('image'))
        {
            $file = AdBanner::find($id);
            if (File::exists(public_path($file->file_name))) {
                File::delete(public_path($file->file_name));
            }
            $image =$request->file('image');
            $title=$image->getClientOriginalName();
            $name = '/banner/'.str_random(10).'.'.$image->getClientOriginalExtension();
            $image->move(public_path().'/banner/', $name);
            $dataFile->file_name = $name;
        }
        $dataFile->save();
        return redirect()->route('bannerImage.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $file = AdBanner::find($id);
        if (File::exists(public_path($file->file_name))) {
            File::delete(public_path($file->file_name));
        }
        $file->delete();
        return redirect()->route('bannerImage.index');
    }
}

resources/views/admin/adbanner/create.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
  <div class="row justify-content-center">
      <div class="col-md-8">
          <div class="box">
              <div class="box-header">
                <h3 class="box-title">Add Ad Banner Image</h3>
              </div>
              <div class="box-body">
              <form  method="POST" action="{{route('bannerImage.store')}}" enctype="multipart/form-data">
                   {{csrf_field()}}
                   <div class="form-group">
                      <label>File Title:</label>
                      <div class="input-group">
                          <div class="input-group-addon">
                            <i class="fa fa-building"></i>
                          </div>
                          <input type="text" class="form-control" name="file_title" placeholder="file title" required>
                      </div>
                   </div>
                   <div class="form-group">
                    <label>Status:</label>
                    <div class="input-group">
                        <div class="input-group-addon">
                          <i class="fa fa-building"></i>
                        </div>
                        <select name="status" class="form-control">
                          <option value="enable">Enable</option>
                          <option value="disable">Disable</option>
                        </select>
                    </div>
                 </div>
                   <div class="form-group">
                      <label>Image:</label>
                      <div class="input-group">
                          <div class="input-group-addon">
                            <i class="fa fa-building"></i>
                          </div>
                          <input type="file" class="form-control" name="image" required>
                      </div>
                   </div>
                  </div>
                   <div class="form-group">
                     <div class="form-input">
                       <input type="submit" class="btn btn-xs btn-primary" value="SUBMIT">
                     </div>
                   </div>
                 </form>
              </div>
          </div>
      </div>
  </div>
</div>
@endSection

resources/views/admin/adbanner/edit.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
  <div class="row justify-content-center">
      <div class="col-md-8">
          <div class="box">
              <div class="box-header">
                <h3 class="box-title">Add Ad Banner Image</h3>
              </div>
              <div class="box-body">
              <form  method="POST" action="{{route('bannerImage.update',$banner->id)}}" enctype="multipart/form-data">
                   {{csrf_field()}}
                   {{method_field('PUT')}}
                   <div class="form-group">
                      <label>File Title:</label>
                      <div class="input-group">
                          <div class="input-group-addon">
                            <i class="fa fa-building"></i>
                          </div>
                          <input type="text" class="form-control" name="file_title" placeholder="file title" value="{{$banner->file_title}}" required>
                      </div>
                   </div>
                   <div class="form-group">
                    <label>Status:</label>
                    <div class="input-group">
                        <div class="input-group-addon">
                          <i class="fa fa-building"></i>
                        </div>
                        <select name="status" class="form-control">
                          <option value="enable" @if($banner->status=='enable') selected @endif>Enable</option>
                          <option value="disable" @if($banner->status=='disable') selected @endif>Disable</option>
                        </select>
                    </div>
                 </div>
                   <div class="form-group">
                      <label>Image:</label>
                      <div class="input-group">
                          <div class="input-group-addon">
                            <i class="fa fa-building"></i>
                          </div>
                          <input type="file" class="form-control" name="image">
                      </div>
                    <img src="{{url($banner->file_name)}}" width="100px">
                   </div>
                  </div>
                   <div class="form-group">
                     <div class="form-input">
                       <input type="submit" class="btn btn-xs btn-primary" value="SUBMIT">
                     </div>
                   </div>
                 </form>
              </div>
          </div>
      </div>
  </div>
</div>
@endSection

resources/views/admin/adbanner/index.blade.php
@extends('layouts.app')
@section('styles')
<!-- DataTables -->
<link rel="stylesheet" href="{{asset('adminlte/bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css')}}">
@endsection
@section('content')
<script src="{{asset('adminlte/bower_components/ckeditor/ckeditor.js')}}"></script>
<div class="container">
  <div class="row justify-content-center">
      <div class="col-md-10">
          <div class="box">
              <div class="box-header">
                <h3 class="box-title">AdBanner</h3>
                <div class="pull-right">
                <a href="{{route('bannerImage.create')}}" class="btn btn-xs btn-primary">Add AdBanner</a>
                </div>
              </div>
              <div class="box-body">
                <table id="dataTable" class="table table-bordered table-hover">
                  <thead>
                   <tr>
                    <th>SN</th>
                    <th>Title</th>
                    <th>File</th>
                    <th>Status</th>
                    <th>Action</th>
                  </tr>
                 </thead>
                 <tbody>
                 @foreach($banners as $k=>$banner)
                 <tr>
                   <td>{{$k+1}}</td>
                   <td>{{$banner->file_title}}</td>
                   <td>
                     <img src="{{url($banner->file_name)}}" alt="{{$banner->file_title}}" width="100px">
                    </td>
                    <td>{{$banner->status}}</td>
                   <td>
                     <form action="{{route('bannerImage.destroy',$banner->id)}}" method="post">
                     <a href="{{route('bannerImage.edit',$banner->id)}}" class="btn btn-xs btn-warning">EDIT</a>
                      {{csrf_field()}}
                      {{method_field('DELETE')}}
                      <input type="submit" class="btn btn-xs btn-danger" value="DELETE">
                     </form>
                   </td>
                 </tr>
                 @endforeach
                 </tbody>
               </table>
               <div class="text-center">
                 {{ $banners->links() }}
               </div>  
            </div>
        </div>
    </div>
  </div>
</div>
@endSection
@section('scripts')
<script src="{{asset('adminlte/bower_components/datatables.net/js/jquery.dataTables.min.js')}}"></script>
<script src="{{asset('adminlte/bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js')}}"></script>
<script>
//data table
    $('#dataTable').DataTable({
      'paging'      : false,
      'lengthChange': false,
      'searching'   : false,
      'ordering'    : true,
      'info'        : false,
      'autoWidth'   : false
    });
</script>
@endsection