routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::group(['middleware' =>['auth']], function(){
Route::get('/', 'HomeController@index')->name('index');
Route::get('/home', 'HomeController@index')->name('home');

Route::resource('/bannerImage', 'AdBannerController');
    
Route::resource('/notice', 'NoticeController');
Route::get('/ajaxGetNoticeFile', 'NoticeController@getNoticeFile')->name('ajaxGetNoticeFile');
Route::delete('/noticefile/{id}/delete', 'NoticeController@deleteNoticeFile')->name('deleteNoticeFile');

Route::resource('/contact', 'ContactController');

Route::resource('/note', 'NoteController');
Route::get('/ajaxGetNoteFile', 'NoteController@getNoteFile')->name('ajaxGetNoteFile');
Route::delete('/notefile/{id}/delete', 'NoteController@deleteNoteFile')->name('deleteNoteFile');

Route::resource('/result', 'ResultController');
Route::get('/ajaxGetResultFile', 'ResultController@getResultFile')->name('ajaxGetResultFile');
Route::delete('/resultfile/{id}/delete', 'ResultController@deleteResultFile')->name('deleteResultFile');

Route::resource('/article', 'ArticleController');
Route::get('/ajaxGetArticleFile', 'ArticleController@getArticleFile')->name('ajaxGetArticleFile');
Route::delete('/articlefile/{id}/delete', 'ArticleController@deleteArticleFile')->name('deleteArticleFile');

Route::resource('/syllabi', 'SyllabusController');
Route::get('/ajaxGetSyllabusFile', 'SyllabusController@getSyllabusFile')->name('ajaxGetSyllabusFile');
Route::delete('/syllabusfile/{id}/delete', 'SyllabusController@deleteSyllabusFile')->name('deleteSyllabusFile');

Route::resource('/question', 'OldQuestionController');
Route::get('/ajaxGetOldQuestionFile', 'OldQuestionController@getOldQuestionFile')->name('ajaxGetOldQuestionFile');
Route::delete('/oldquestionfile/{id}/delete', 'OldQuestionController@deleteOldQuestionFile')->name('deleteOldQuestionFile');

Route::resource('/taxonomies', 'TaxonomyController');
Route::get('/ajaxGetTaxonomyFile', 'TaxonomyController@getTaxonomyFile')->name('ajaxGetTaxonomyFile');
Route::delete('/taxonomyfile/{id}/delete', 'TaxonomyController@deleteTaxonomyFile')->name('deleteTaxonomyFile');

Route::resource('/capsule', 'CapsuleController');
Route::get('/ajaxGetCapsuleFile', 'CapsuleController@getCapsuleFile')->name('ajaxGetCapsuleFile');
Route::delete('/capsulefile/{id}/delete', 'CapsuleController@deleteCapsuleFile')->name('deleteCapsuleFile');


Route::resource('/department', 'DepartmentController');
Route::resource('/category', 'CategoryController');

Route::get('/booking', 'BookingController@index')->name('booking.index');
Route::get('/booking/{id}', 'BookingController@view')->name('booking.view');
Route::get('/booking/delete/{id}', 'BookingController@delete')->name('booking.destroy');
});

app/AdBanner.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class AdBanner extends Model
{
    protected $table = 'ad_banners';    
}

app/Article.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Article extends Model
{
    public function article_file(){
    	return $this->hasMany('App\ArticleFile');
    }
}

app/ArticleFile.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class ArticleFile extends Model
{
    //
}

app/Booking.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Booking extends Model
{
    //
}

app/Capsule.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Capsule extends Model
{
    public function category(){
    	return $this->belongsTo('App\Category');
    }
    public function capsule_file(){
    	return $this->hasMany('App\CapsuleFile');
    }
}

app/CapsuleFile.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class CapsuleFile extends Model
{
    //
}

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    //
}

app/Contact.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Contact extends Model
{
    //
}

app/Department.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Department extends Model
{
    //
}

app/Note.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Note extends Model
{
	public function department(){
    	return $this->belongsTo('App\Department');
    }
    public function semester(){
    	return $this->belongsTo('App\Semester');
    }
    public function note_file(){
    	return $this->hasMany('App\NoteFile');
    }
}

app/NoteFile.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class NoteFile extends Model
{
    
}

app/Notice.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Notice extends Model
{
    public function notice_file(){
    	return $this->hasMany('App\NoticeFile','notice_id');
    }
}

app/NoticeFile.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class NoticeFile extends Model
{
    
}

app/NoticeImage.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class NoticeImage extends Model
{
    //
}

app/Result.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Result extends Model
{
    public function result_file(){
    	return $this->hasMany('App\ResultFile');
    }
}

app/ResultFile.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class ResultFile extends Model
{
    //
}

app/Semester.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Semester extends Model
{
    //
}

app/Syllabus.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Syllabus extends Model
{
    public function syllabus_file(){
    	return $this->hasMany('App\SyllabusFile');
    }
}

app/Taxonomy.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Taxonomy extends Model
{
    public function taxonomy_file(){
    	return $this->hasMany('App\TaxonomyFile');
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

resources/views/home.blade.php
@extends('layouts.app')
@section('content')
<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
      Dashboard
      <small>Control panel</small>
    </h1>
    <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class="active">Dashboard</li>
    </ol>
  </section>

  <!-- Main content -->
  <section class="content">
    <!-- Small boxes (Stat box) -->
    {{-- <div class="row">
      <div class="col-lg-3 col-xs-6">
        <!-- small box -->
        <div class="small-box bg-aqua">
          <div class="inner">
            <h3>150</h3>

            <p>Open Ticket</p>
          </div>
          <div class="icon">
            <i class="ion ion-bag"></i>
          </div>
          <a href="#" class="small-box-footer">More info <i class="fa fa-arrow-circle-right"></i></a>
        </div>
      </div>
      <!-- ./col -->
      <div class="col-lg-3 col-xs-6">
        <!-- small box -->
        <div class="small-box bg-green">
          <div class="inner">
            <h3>53<sup style="font-size: 20px">%</sup></h3>
            <p>Ticket Close</p>
          </div>
          <div class="icon">
            <i class="ion ion-stats-bars"></i>
          </div>
          <a href="#" class="small-box-footer">More info <i class="fa fa-arrow-circle-right"></i></a>
        </div>
      </div>
      <!-- ./col -->
      <div class="col-lg-3 col-xs-6">
        <!-- small box -->
        <div class="small-box bg-yellow">
          <div class="inner">
            <h3>44</h3>

            <p>Users</p>
          </div>
          <div class="icon">
            <i class="ion ion-person-add"></i>
          </div>
          <a href="#" class="small-box-footer">More info <i class="fa fa-arrow-circle-right"></i></a>
        </div>
      </div>
      <!-- ./col -->
      <div class="col-lg-3 col-xs-6">
        <!-- small box -->
        <div class="small-box bg-red">
          <div class="inner">
            <h3>65</h3>

            <p>Unique Visitors</p>
          </div>
          <div class="icon">
            <i class="ion ion-pie-graph"></i>
          </div>
          <a href="#" class="small-box-footer">More info <i class="fa fa-arrow-circle-right"></i></a>
        </div>
      </div>
      <!-- ./col -->
    </div> --}}
    <!-- /.row -->
    <!-- Main row -->
    
  </section>
  <!-- /.content -->
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html>
<head>
  @include('layouts.head')
</head>
<body class="hold-transition skin-blue sidebar-mini">
<div class="wrapper">
  @include('layouts.header')
  <!-- Left side column. contains the logo and sidebar -->
  @include('layouts.sidebar')

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    @yield('content')
  </div>
  <!-- /.content-wrapper -->
  @include('layouts.foot')
  @yield('scripts')
</body>
</html>

resources/views/layouts/foot.blade.php
<footer class="main-footer">
  <div class="pull-right hidden-xs">
    <b>Version</b> 2.4.13
  </div>
  <strong>Copyright &copy; 2014-2019 <a href="https://adminlte.io">AdminLTE</a>.</strong> All rights
  reserved.
</footer>
</div>
<!-- ./wrapper -->
<!-- jQuery 3 -->
<script src="{{asset('adminlte/bower_components/jquery/dist/jquery.min.js')}}"></script>
<!-- jQuery UI 1.11.4 -->
<script src="{{asset('adminlte/bower_components/jquery-ui/jquery-ui.min.js')}}"></script>
<!-- Bootstrap 3.3.7 -->
<script src="{{asset('adminlte/bower_components/bootstrap/dist/js/bootstrap.min.js')}}"></script>
<!-- AdminLTE App -->
<script src="{{asset('adminlte/dist/js/adminlte.min.js')}}"></script>

resources/views/layouts/head.blade.php
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Agriculture App</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  <!-- Bootstrap 3.3.7 -->
  <link rel="stylesheet" href="{{asset('adminlte/bower_components/bootstrap/dist/css/bootstrap.min.css')}}">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{{asset('adminlte/bower_components/font-awesome/css/font-awesome.min.css')}}">
  <!-- Ionicons -->
  <link rel="stylesheet" href="{{asset('adminlte/bower_components/Ionicons/css/ionicons.min.css')}}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{{asset('adminlte/dist/css/AdminLTE.min.css')}}">
  <!-- AdminLTE Skins. Choose a skin from the css/skins
       folder instead of downloading all of them to reduce the load. -->
  <link rel="stylesheet" href="{{asset('adminlte/dist/css/skins/_all-skins.min.css')}}">
  <link rel="icon" href="{{asset('adminlte/dist/img/user2-160x160.jpg')}}" type="image/gif" sizes="16x16">

  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">

resources/views/layouts/header.blade.php
<header class="main-header">
  <!-- Logo -->
  <a href="javascript:void(0)" class="logo">
    <!-- mini logo for sidebar mini 50x50 pixels -->
    <span class="logo-mini"><b>A</b>pp</span>
    <!-- logo for regular state and mobile devices -->
    <span class="logo-lg"><b>Agro</b>App</span>
  </a>
  <!-- Header Navbar: style can be found in header.less -->
  <nav class="navbar navbar-static-top">
    <!-- Sidebar toggle button-->
    <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
      <span class="sr-only">Toggle navigation</span>
    </a>

    <div class="navbar-custom-menu">
      <ul class="nav navbar-nav">
        <!-- User Account: style can be found in dropdown.less -->
        <li class="dropdown user user-menu">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            @auth
            <img src="{{asset('adminlte/dist/img/user2-160x160.jpg')}}" class="user-image" alt="User Image">
            <span class="hidden-xs">{{Auth::user()->name}}</span>
            @endauth
          </a>
          <ul class="dropdown-menu">
            <!-- User image -->
            <li class="user-header">
              <img src="{{asset('adminlte/dist/img/user2-160x160.jpg')}}" class="img-circle" alt="User Image">

              <p>
                @auth{{Auth::user()->name}}@endauth
                {{-- <small>Member since Nov. 2012</small> --}}
              </p>
            </li>
            <!-- Menu Footer-->
            <li class="user-footer">
              <div class="pull-right">
                <a href="#" 
                class="btn btn-default btn-flat" 
                href="{{ route('logout') }}"
                onclick="event.preventDefault();
                              document.getElementById('logout-form').submit();">Sign out</a>
                <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                  {{csrf_field()}}
              </form>
              </div>
            </li>
          </ul>
        </li>
      </ul>
    </div>
  </nav>
</header>

resources/views/layouts/sidebar.blade.php
<aside class="main-sidebar">
  <!-- sidebar: style can be found in sidebar.less -->
  <section class="sidebar">
    <!-- Sidebar user panel -->
    <div class="user-panel">
      <div class="pull-left image">
        <img src="{{asset('adminlte/dist/img/user2-160x160.jpg')}}" class="img-circle" alt="User Image">
      </div>
      <div class="pull-left info">
        @auth
        <p>{{Auth::user()->name}}</p>
        @endauth
      </div>
    </div>
    <!-- sidebar menu: : style can be found in sidebar.less -->
    <ul class="sidebar-menu" data-widget="tree">s
      <li class="header">MAIN NAVIGATION</li>
      <li>
        <a href="{{route('booking.index')}}">
          <i class="fa fa-th"></i> <span>Booking</span>
        </a>
      </li>
      <li @if(Request::segment(1)=='department') class="active" @endif>
        <a href="{{route('department.index')}}">
          <i class="fa fa-building"></i> <span>Department</span>
        </a>
      </li>
      <li @if(Request::segment(1)=='bannerImage') class="active" @endif>
        <a href="{{route('bannerImage.index')}}">
          <i class="fa fa-image"></i> <span>Ad Banner</span>
        </a>
      </li>
      <li @if(Request::segment(1)=='notice') class="active" @endif>
        <a href="{{route('notice.index')}}">
          <i class="fa fa-file-pdf-o"></i> <span>Notices</span>
        </a>
      </li>
      <li @if(Request::segment(1)=='note') class="active" @endif>
        <a href="{{route('note.index')}}">
          <i class="fa fa-files-o"></i> <span>Notes</span>
        </a>
      </li>
      <li @if(Request::segment(1)=='article') class="active" @endif>
        <a href="{{route('article.index')}}">
          <i class="fa fa-newspaper-o"></i> <span>Article</span>
        </a>
      </li>
      <li @if(Request::segment(1)=='result') class="active" @endif>
        <a href="{{route('result.index')}}">
          <i class="fa fa-sticky-note-o"></i> <span>Result</span>
        </a>
      </li>
      <li @if(Request::segment(1)=='syllabi') class="active" @endif>
        <a href="{{route('syllabi.index')}}">
          <i class="fa fa-file-o"></i> <span>Syllabus</span>
        </a>
      </li>
      <li @if(Request::segment(1)=='contact') class="active" @endif>
        <a href="{{route('contact.index')}}">
          <i class="fa fa-envelope-o"></i> <span>Message</span>
        </a>
      </li>
      <li @if(Request::segment(1)=='question') class="active" @endif>
        <a href="{{route('question.index')}}">
          <i class="fa fa-question-circle-o"></i> <span>OldQuestion</span>
        </a>
      </li>
      <li @if(Request::segment(1)=='taxonomies') class="active" @endif>
        <a href="{{route('taxonomies.index')}}">
          <i class="fa fa-file-pdf-o"></i> <span>Taxonomy</span>
        </a>
      </li>
      <li class="treeview"  @if(Request::segment(1)=='category') class='active' @endif>
        <a href="#">
          <i class="fa fa-dashboard"></i> <span>Entrance Preparation Capsule</span>
          <span class="pull-right-container">
            <i class="fa fa-angle-left pull-right"></i>
          </span>
        </a>
        <ul class="treeview-menu">
          <li @if(Request::segment(1)=='category') class="active" @endif><a href="{{route('category.index')}}"><i class="fa fa-circle-o"></i>Category</a></li>
          <li @if(Request::segment(1)=='capsule') class="active" @endif><a href="{{route('capsule.index')}}"><i class="fa fa-circle-o"></i> Capsule Entry</a></li>
        </ul>
      </li>
    </ul>
  </section>
  <!-- /.sidebar -->
</aside>